security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls: 
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            anonymous: true
            json_login:
                username_path: username
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator

        main:
            anonymous: true
            lazy: true
            provider: app_user_provider

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/api/login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api$ , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin, roles:[ROLE_ADMIN], methods:[POST,GET,PUT,PATCH,DELETE] }
        - { path: ^/api/formateurs/briefs,roles:[ROLE_]}
        #- { path: ^/api/formateurs/briefs,roles:[ROLE_FORMATEUR]}
        #- { path: ^/api/formateurs/promo/id/groupe/id/briefs, roles:[ROLE_FORMATEUR,ROLE_CM]}        
